.base: &base
  forwardAgent: true
  multiplexing: true

104.248.150.199: &dev1
  <<: *base
  stage: "develop"
  user: "root"
  port: 22
  identityFile: "~/.ssh/personal_1"
  # eng
  #  deploy_path: "/var/www/news/{{application}}"
  #  branch: "develop"
  # vi
  deploy_path: "/var/www/{{application}}"
  branch: "develop"
